

; Cat.asm
; For each input device, output all input to standard output.

.ALIAS EXT_BUFFER_IN 18
.ALIAS ALU_STATUS 20
.ALIAS NUM_EXT_BUFF 21
.ALIAS CURRENT_BUFFER 0x0
.ALIAS _TEMP 0x1
.ALIAS CURRENT_BYTE_A 0x2
.ALIAS CURRENT_BYTE_B 0x3

.ALIAS ALU_OVERFLOW_MASK 0x01

; Program start

JMP PROG_START ; RESET
JMP error ; TIMER_TICK
JMP error ; BAD_MEM_ACCESS
JMP error ; STACK_OVERFLOW
JMP error ; STACK_UNDERFLOW
JMP error ; BAD_INS
JMP END_FILE ; FAILED_EXT_ACCESS

error:

shutdown:
    SHUTDOWN

END_FILE:
    PRINTFLUSH
    INC CURRENT_BUFFER

    GTEQ _TEMP CURRENT_BUFFER NUM_EXT_BUFF
    CJMP _TEMP shutdown

    SET CURRENT_BYTE_A 0
    SET CURRENT_BYTE_B 0
    POP _TEMP ; Pop from the return stack so we can pick our own entry point
    JMP PRINT_FILE
    
PROG_START:
    SET CURRENT_BUFFER 0
    SET CURRENT_BYTE_A 0
    SET CURRENT_BYTE_B 0
    
    CJMP NUM_EXT_BUFF PRINT_FILE
    SHUTDOWN

PRINT_FILE:
    EXTFETCH CURRENT_BUFFER CURRENT_BYTE_A CURRENT_BYTE_B

    PRINTL EXT_BUFFER_IN

    INC CURRENT_BYTE_B

    MOV _TEMP ALU_STATUS
    ANDI _TEMP ALU_OVERFLOW_MASK
    CJMP _TEMP INC_A
    RJMP PRINT_FILE

INC_A:
    INC CURRENT_BYTE_A
    RJMP PRINT_FILE

