

; Cat.asm
; For each input device, output all input to standard output.

.ALIAS EXT_BUFFER_IN 0x02
.ALIAS ALU_STATUS 0x04
.ALIAS NUM_EXT_BUFF 0x05
.ALIAS CURRENT_BUFFER 0x10
.ALIAS _TEMP 0x11
.ALIAS CURRENT_BYTE_A 0x12
.ALIAS CURRENT_BYTE_B 0x13

.ALIAS ALU_OVERFLOW_MASK 0x01

; Program start

JMP PROG_START ; RESET
JMP error ; TIMER_TICK
JMP error ; BAD_MEM_ACCESS
JMP error ; STACK_OVERFLOW
JMP error ; STACK_UNDERFLOW
JMP error ; STACK_OVERFLOW
JMP error ; BAD_INS
JMP END_FILE ; FAILED_EXT_ACCESS

error:
    SHUTDOWN

END_FILE:
    PRINTFLUSH
    INC CURRENT_BUFFER

    SUB _TEMP CURRENT_BUFFER NUM_EXT_BUFF
    CJMP _TEMP END_FILE_cont
    SHUTDOWN

END_FILE_cont:
    SET CURRENT_BYTE_A 0
    SET CURRENT_BYTE_B 0
    POP _TEMP ; Pop from the return stack so we can pick our own entry point
    JMP PRINT_FILE
    
PROG_START:
    SET CURRENT_BUFFER 0
    SET CURRENT_BYTE_A 0
    SET CURRENT_BYTE_B 0
    
    CJMP NUM_EXT_BUFF PRINT_FILE
    SHUTDOWN

PRINT_FILE:
    EXTFETCH CURRENT_BUFFER CURRENT_BYTE_A CURRENT_BYTE_B

    PRINTL EXT_BUFFER_IN

    INC CURRENT_BYTE_B

    MOV _TEMP ALU_STATUS
    ANDI _TEMP ALU_OVERFLOW_MASK
    CJMP _TEMP INC_A
    RJMP PRINT_FILE

INC_A:
    INC CURRENT_BYTE_A
    RJMP PRINT_FILE

